### ISSUE TITLE
Error when using make command

### ISSUE THREAD

**Issue by Bhavy11111** [kimbo/bluesnarfer#5] opened 2022-03-18 08:01 UTC
~/bluesnarfer $ make
gcc -Iinclude -W -g3 src/bluesnarfer.c -lbluetooth -o bluesnarfer
src/bluesnarfer.c:34:10: fatal error: 'bluetooth/bluetooth.h' file not found
#include <bluetooth/bluetooth.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:11: bluesnarfer] Error 1

**Comment by kimbo** [comment] 2022-03-20 17:29
duplicate of https://github.com/kimbo/bluesnarfer/issues/1. Check out that one for help

**Closed as completed by kimbo** 2022-03-20 17:29 UTC
